[theme]
base="dark"

# Background color for the main content area
backroundColor="#1F2233"

# Primary accent for interactive elements
primaryColor="#00769B"

# Background color for sidebar and most interactive widgets
secondaryBackroundColor="#8E0079"

# Color used for almost all text
textColor = '#FFFFFF'

font="sans serif"



